print("Contador de numero")
numero = int(input("Digite um numero: "))
for i in range(numero):
    print("n°", i)
print("")
print("Soma")
num1 = int(input("Digite um numero: "))
num2 = int(input("Digite outro numero: "))
print("A soma é igual a: ", num1+num2)
print("")
print("Subtracao")
sub1 = int(input("Digite um numero: "))
sub2 = int(input("Digite outro numero: "))
print("O resultado é igual a: ", sub1-sub2)
print("")
print("Multiplicaçao")
mult1 = int(input("digite um numero: "))
mult2 = int(input("digite outro numero: "))
print("O resultado é: ", mult1*mult2)
print("")
print("Divisao")
div1 = int(input("Digite um numero: "))
div2 = int(input("Digite um outro numero: "))
print("O resultado é: ", div1/div2)
print("")
print("modulo")
mod1 = int(input("Digite um numero: "))
mod2 = int(input("Digite outro numero: "))
print("o resultado é: ",mod1 % mod2)
print("")
print("Expotenciaçao")
exp1 = int(input("Digite um numero: "))
exp2 = int(input("Digite outro numero: "))
print("")
print("A cima estao todos os resultados!")
print("")
print("Faturamento do mes")
vendas = int(input("digite o valor das vendas: "))
custoCarga = int(input("digite o custo: "))
salarios = int(input("Digite o valor pago de salario: "))
contas = int(input("Digite o valor das contas a pagar: "))
print("O lucro foi: ", vendas - custoCarga - salarios - contas)
print("Este foi o total mensal")
print("")
