print("Notas")
N1 = float(input("Digite a primeira nota: "))
N2 = float(input("Digite a segunda nota: "))
N3 = float(input("Digite a terceira nota: "))
N4 = float(input("Digite a quarta nota: "))
print((N1 + N2 + N3 + N4) / 4 )
print("")

print("Area Quadrado")
lado = float(input("Digite o lado: "))
print("A area é; ",lado ** 2)
print("")

num1 = int(input("Questao A: Digite um numero: "))
num2 = int(input("Questao B: Digite um outro numero: "))
num3 = float(input("Questao C: Digite outro numero: "))
print(("Questao A resultado: "),( num2 / 2 num1 * 2 * ))
print(("resultado questao B: "),(num1 * 3) + num3)
print(("Resultado questao C: "), num3 * num3 * num3)
